/* *****************************************************************************
"Numerical Recipes in C" (Cambridge Univ. Press)
The Art of Scientific Computing, 2nd Edition, 1992 p 303~304
by W.H. Press, S.A. Teukolsky, W.T. Vetterling, and B.P. Flannery
***************************************************************************** */
#include "nrutil.h"
/* *****************************************************************************
Returns a uniform random deviate in the range 0.0 to 1.0, generated by
pseudo-DES (DES-like) hashing of the 64-bit word (idums,idum) , where idums was
set by a previous call with negative idum . Also increments idum. Routine can be
used to generate a random sequence by successive calls, leaving idum unaltered
between calls; or it can randomly access the nth deviate in a sequence by
calling with idum = n. Different sequences are initialized by calls with
differing negative values of idum .
***************************************************************************** */
double ran4(long int *idum){
   unsigned long irword, itemp, lword;
   static long idums = 0L;
   float *tmp;
   /* The hexadecimal constants jflone and jflmsk below are used to produce a
   floating number between 1. and 2. by bitwise masking. They are
   machine-dependent. See text. */
#if defined(vax) || defined(_vax_) || defined(__vax__) || defined(VAX)
   static unsigned long jflone = 0x00004080;
   static unsigned long jflmsk = 0xffff007f;
#else
   static unsigned long jflone = 0x3f800000;
   static unsigned long jflmsk = 0x007fffff;
#endif

   if (*idum < 0L){ // Reset idums and prepare to return the first
      idums = -(*idum); // deviate in its sequence.
      *idum = 1L;
   }
   irword = (*idum);
   lword = idums;
   psdes(&lword, &irword);
   itemp = jflone | (jflmsk & irword);
   ++(*idum);
   tmp = (float*)&itemp;
   return (double)(*tmp) - 1.0;
}
/* *****************************************************************************
Period \approx ?
Relative (ran0) time execution = 4.0
ran4(&idum) \in [0, 1]
***************************************************************************** */
