#!/bin/bash

# Script to compile libDamiao

cd "$(dirname $0)"

# implementation list to compile
file="MT19937.c "
file+="atoc.c "

# Compile implementations
#    with gcc
gcc -c -g $file -std=c99 -lm

# Make a static library with archiver
ar rs libdamiao.a *.o

# Remove object files
rm *.o

exit 0
