#!/bin/bash

# Script to compile libDamiao

cd "$(dirname $0)"

# implementation list to compile
file="MT19937.c "
file+="atoc.c "
file+="atoc.c "
file+="correlated_w_fourier.c "
file+="correlated_w_bernoulli.c "
file+="correlated_w_distance.c "
file+=" "
file+=" "

# Compile implementations
#    with gcc
gcc -c -g $file -std=c99 -lm

# Make a static library with archiver
ar rs libdamiao.a *.o

# Remove object files
rm *.o

exit 0
